name: Medusa-CI

on: workflow_dispatch

jobs:
  app-build:
    runs-on: self-hosted
    env:
      DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          
          cd my-medusa-store
          npm install
          
      - name: Building
        run: |
          cd my-medusa-store
          npx medusa build


  docker-build:
     runs-on: self-hosted
     needs:  
       - app-build
     steps:
       - name: Docker building image
         run: |
            export DATABASE_URL=`sudo  aws rds describe-db-instances   --db-instance-identifier database-medusa \
            --query 'DBInstances[0].Endpoint.Address' --output text` 
            export REDIS_URL=`sudo aws elasticache describe-replication-groups   --replication-group-id my-redis-medusa \
            --query 'ReplicationGroups[0].ConfigurationEndpoint.Address'   --output text`
          
            cd my-medusa-store
            cat medusa-config.ts
            cat Dockerfile
            sudo docker build -t ecrmedusa:v1 .
            sudo docker tag ecrmedusa:v1 974871161012.dkr.ecr.ap-south-1.amazonaws.com/ecr-github-action/medusa:latest 

            
  docker-push:
        runs-on: self-hosted
        needs:
          - docker-build
        steps:
          - name: Pushing to docker hub
            run: |
                sudo docker push 974871161012.dkr.ecr.ap-south-1.amazonaws.com/ecr-github-action/medusa:latest

         
