name: Medusa-CI
on: workflow_dispatch
jobs:
  git_checking-out:
    runs-on: self-hosted
    steps:
      - name: Checking Out
        uses: actions/checkout@v4
  medusa-build:
   runs-on: self-hosted
   steps:
    - name: Building app
      run: sudo npx medusa build
