name: Medusa-CI
on: workflow_dispatch
jobs:

  git_checking-out:
    runs-on: self-hosted
    steps:
      - name: Checking Out
        uses: actions/checkout@v4
  medusa-build:
   runs-on: self-hosted
   steps: 
     - uses: actions/setup-node@v4
       with:
           node-version: '20'
     - name: Building app
       run: |
            cd my-medusa-store
            npx medusa build
