name: Deploy to ECS

on:
  workflow_run:
    workflows: ["Medusa-CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Fetch current task definition and create new revision
        run: |

          TASK_NAME="medusa-task"
          sudo aws ecs describe-task-definition --task-definition $TASK_NAME --output json > task-def.json
          cat task-def.json
         
          IMAGE="mushahid144/mymedusa:v1"
          jq --arg IMAGE "$IMAGE" '.taskDefinition | {
           family: .family,
           networkMode: .networkMode,
           executionRoleArn: .executionRoleArn,
           containerDefinitions: .containerDefinitions,
           requiresCompatibilities: .requiresCompatibilities,
           cpu: .cpu,
           memory: .memory
            }' task-def.json > new-task-def.json

          sudo aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: Update ECS service to use new task definition
        run: |
          sudo aws ecs update-service \
            --cluster medusa-cluster \
            --service medusa_ecs_service \
            --task-definition medusa-task \
            --force-new-deployment
