name: Testing

on: workflow_dispatch

jobs:
  app-build:
    runs-on: self-hosted
    env:
      DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - name: testing
        run: |
            export DATABASE_URL=`sudo  aws rds describe-db-instances   --db-instance-identifier database-medusa \
            --query 'DBInstances[0].Endpoint.Address' --output text` 
            export REDIS_URL=`sudo aws elasticache describe-replication-groups   --replication-group-id my-redis-medusa \
            --query 'ReplicationGroups[0].ConfigurationEndpoint.Address'   --output text`

            echo $DATABASE_URL
            echo $REDIS_URL
