name: Medusa-CI

on: workflow_dispatch

jobs:
  app-build:
    runs-on: self-hosted
    env:
      DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - name: testing
        run: |
            export DATABASE_URL=`sudo  aws rds describe-db-instances   --db-instance-identifier database-medusa \
            --query 'DBInstances[0].Endpoint.Address' --output text` 
            echo $DATABASE_USERNAME
            echo $DATABASE_PASSWORD
            echo $DATABASE_URL
